### ISSUE TITLE
Page 203 Labyrinthine layer 'Incorrect' confusingly worded

### ISSUE THREAD

**Issue by MayCauseAnnihilation** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#149] opened 2021-04-27 10:38 UTC
The Labyrinthine layer for Eidolons is weirdly worded, not sure where the contested check comes in. Also apparently it's supposed to have a 1/turn limit according to the rules section.

**Comment by KaiTave** [comment] 2021-04-27 23:31
A ticket already exists regarding this issue: https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/133

Also to clarify, all actions have an inherent 1/turn limit because the game forbids duplicate use of the same action barring free actions and reactions, which is what the wording in this layer is referring to. When characters make incorrect guesses, the Eidolon uses INCORRECT against them as a reaction, and therefore ignores the usual action restrictions it might have.

**Comment by Piezoelectric** [comment] 2021-05-17 16:31
Closed as duplicate of 133

**Closed as completed by Piezoelectric** 2021-05-17 16:31 UTC
Labels: duplicate
