### ISSUE TITLE
Page 180 - PEBCAC Statblock Color Formatting Error

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#120] opened 2021-04-03 08:04 UTC
The Kidd's PEBCAC is a Quick Tech granting system, and therefore it should use the same purple color and Tech Action header iconography as, for example, the Field-Approved, Brass-Ignorant Modifications on the same page.

**Comment by Piezoelectric** [comment] 2021-04-04 15:25
Duplicate of https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/4

**Closed as completed** 2021-04-04 18:59 UTC
Labels: duplicate
